import { Injectable } from '@angular/core';
import {
  HttpInterceptor,
  HttpEvent,
  HttpHandler,
  HttpRequest,
  HttpHeaders,
} from '@angular/common/http';
import { Observable } from 'rxjs';

@Injectable({
  providedIn: 'root',
})
export class CustomHttpInterceptorService implements HttpInterceptor {
  intercept(
    req: HttpRequest<any>,
    next: HttpHandler
  ): Observable<HttpEvent<any>> {
    if (localStorage.getItem('access_token')) {
      console.log('Er is een access_token, ga verder met Headers:');
      let at = localStorage.getItem('access_token').toString();
      let myheaders = new HttpHeaders({
        'Content-Type': 'application/json',
        Authorization:
          'Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICIyUVBNRFAzc09fbDlkWXQwLWlWb2hmSTNWb3ZNR2pTS0tvSVVkcVdCVFBNIn0.eyJleHAiOjE1ODk2NTQ1MDUsImlhdCI6MTU4OTYzNjUwNSwiYXV0aF90aW1lIjoxNTg5NjM2NTA1LCJqdGkiOiJlOWJhYzMyNy1hNGVhLTRkOTctOWJjNC1jMDEzMWY3NjQzMGUiLCJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjgwODAvYXV0aC9yZWFsbXMvRHJlYW1CaWtlS2V5Y2xvYWsiLCJhdWQiOlsicmVhbG0tbWFuYWdlbWVudCIsInVzZXItc2VydmljZSIsImFjY291bnQiXSwic3ViIjoiNjFhMTRlNzEtZjRmZC00ODY4LTk4NjYtZTY4YjljMTBjNjFkIiwidHlwIjoiQmVhcmVyIiwiYXpwIjoibG9naW5hcHAiLCJzZXNzaW9uX3N0YXRlIjoiMTQ5NjBiMDItOTFmZC00MTE1LWJmMzMtNDYyNDU0OTAzNTNmIiwiYWNyIjoiMSIsImFsbG93ZWQtb3JpZ2lucyI6WyJodHRwOi8vbG9jYWxob3N0OjIwMjAiXSwicmVhbG1fYWNjZXNzIjp7InJvbGVzIjpbIm9mZmxpbmVfYWNjZXNzIiwidW1hX2F1dGhvcml6YXRpb24iLCJVU0VSIl19LCJyZXNvdXJjZV9hY2Nlc3MiOnsicmVhbG0tbWFuYWdlbWVudCI6eyJyb2xlcyI6WyJ2aWV3LWlkZW50aXR5LXByb3ZpZGVycyIsInZpZXctcmVhbG0iLCJtYW5hZ2UtaWRlbnRpdHktcHJvdmlkZXJzIiwiaW1wZXJzb25hdGlvbiIsInJlYWxtLWFkbWluIiwiY3JlYXRlLWNsaWVudCIsIm1hbmFnZS11c2VycyIsInF1ZXJ5LXJlYWxtcyIsInZpZXctYXV0aG9yaXphdGlvbiIsInF1ZXJ5LWNsaWVudHMiLCJxdWVyeS11c2VycyIsIm1hbmFnZS1ldmVudHMiLCJtYW5hZ2UtcmVhbG0iLCJ2aWV3LWV2ZW50cyIsInZpZXctdXNlcnMiLCJ2aWV3LWNsaWVudHMiLCJtYW5hZ2UtYXV0aG9yaXphdGlvbiIsIm1hbmFnZS1jbGllbnRzIiwicXVlcnktZ3JvdXBzIl19LCJsb2dpbmFwcCI6eyJyb2xlcyI6WyJ1bWFfcHJvdGVjdGlvbiIsIkFETUlOIl19LCJ1c2VyLXNlcnZpY2UiOnsicm9sZXMiOlsiVVNFUiJdfSwiYWNjb3VudCI6eyJyb2xlcyI6WyJtYW5hZ2UtYWNjb3VudCIsIm1hbmFnZS1hY2NvdW50LWxpbmtzIiwidmlldy1wcm9maWxlIl19fSwic2NvcGUiOiJvcGVuaWQgZW1haWwgcHJvZmlsZSIsImVtYWlsX3ZlcmlmaWVkIjp0cnVlLCJ1c2VyX25hbWUiOiJyZW15IiwibmFtZSI6IlJlbXkgZGUgQWRtaW4iLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJyZW15IiwiZ2l2ZW5fbmFtZSI6IlJlbXkiLCJmYW1pbHlfbmFtZSI6ImRlIEFkbWluIiwiZW1haWwiOiJqbWd3aXRsb3hAaG90bWFpbC5jb20ifQ.b4Gq5c-1dPRYzwKIuzrrfCEq5X0iie6NAbrZApjKWIAZ0fxt-1iJnqKc_9u94vJkN2BNojzRPvWFQnQyWx6t3a_J1LuRX2zP_P70IrHnqyM0gMc7NSpscQ6fr2iWb2UMg551OpkFaANd3DxaIeEj4QbxryloaRK2NbZSTOlxgXUOjJ_jbPJhQXXNdiIFur11D0C_hw1ABp3iCbCIz0lGwa6c6wKJRXmXKYrJ57WM9-srOYN4gArCrFkLIj_LiN6B1-hPWtgQTngXK2JPuRn75TNp0A0xHrwjsFSDxdaPw53xdLDBPkG-PenXNtW_uaoQPhu9B7l3ufXXP_Rh_quV-w',
        access_token:
          'eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICIyUVBNRFAzc09fbDlkWXQwLWlWb2hmSTNWb3ZNR2pTS0tvSVVkcVdCVFBNIn0.eyJleHAiOjE1ODk2NTQ1MDUsImlhdCI6MTU4OTYzNjUwNSwiYXV0aF90aW1lIjoxNTg5NjM2NTA1LCJqdGkiOiJlOWJhYzMyNy1hNGVhLTRkOTctOWJjNC1jMDEzMWY3NjQzMGUiLCJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjgwODAvYXV0aC9yZWFsbXMvRHJlYW1CaWtlS2V5Y2xvYWsiLCJhdWQiOlsicmVhbG0tbWFuYWdlbWVudCIsInVzZXItc2VydmljZSIsImFjY291bnQiXSwic3ViIjoiNjFhMTRlNzEtZjRmZC00ODY4LTk4NjYtZTY4YjljMTBjNjFkIiwidHlwIjoiQmVhcmVyIiwiYXpwIjoibG9naW5hcHAiLCJzZXNzaW9uX3N0YXRlIjoiMTQ5NjBiMDItOTFmZC00MTE1LWJmMzMtNDYyNDU0OTAzNTNmIiwiYWNyIjoiMSIsImFsbG93ZWQtb3JpZ2lucyI6WyJodHRwOi8vbG9jYWxob3N0OjIwMjAiXSwicmVhbG1fYWNjZXNzIjp7InJvbGVzIjpbIm9mZmxpbmVfYWNjZXNzIiwidW1hX2F1dGhvcml6YXRpb24iLCJVU0VSIl19LCJyZXNvdXJjZV9hY2Nlc3MiOnsicmVhbG0tbWFuYWdlbWVudCI6eyJyb2xlcyI6WyJ2aWV3LWlkZW50aXR5LXByb3ZpZGVycyIsInZpZXctcmVhbG0iLCJtYW5hZ2UtaWRlbnRpdHktcHJvdmlkZXJzIiwiaW1wZXJzb25hdGlvbiIsInJlYWxtLWFkbWluIiwiY3JlYXRlLWNsaWVudCIsIm1hbmFnZS11c2VycyIsInF1ZXJ5LXJlYWxtcyIsInZpZXctYXV0aG9yaXphdGlvbiIsInF1ZXJ5LWNsaWVudHMiLCJxdWVyeS11c2VycyIsIm1hbmFnZS1ldmVudHMiLCJtYW5hZ2UtcmVhbG0iLCJ2aWV3LWV2ZW50cyIsInZpZXctdXNlcnMiLCJ2aWV3LWNsaWVudHMiLCJtYW5hZ2UtYXV0aG9yaXphdGlvbiIsIm1hbmFnZS1jbGllbnRzIiwicXVlcnktZ3JvdXBzIl19LCJsb2dpbmFwcCI6eyJyb2xlcyI6WyJ1bWFfcHJvdGVjdGlvbiIsIkFETUlOIl19LCJ1c2VyLXNlcnZpY2UiOnsicm9sZXMiOlsiVVNFUiJdfSwiYWNjb3VudCI6eyJyb2xlcyI6WyJtYW5hZ2UtYWNjb3VudCIsIm1hbmFnZS1hY2NvdW50LWxpbmtzIiwidmlldy1wcm9maWxlIl19fSwic2NvcGUiOiJvcGVuaWQgZW1haWwgcHJvZmlsZSIsImVtYWlsX3ZlcmlmaWVkIjp0cnVlLCJ1c2VyX25hbWUiOiJyZW15IiwibmFtZSI6IlJlbXkgZGUgQWRtaW4iLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJyZW15IiwiZ2l2ZW5fbmFtZSI6IlJlbXkiLCJmYW1pbHlfbmFtZSI6ImRlIEFkbWluIiwiZW1haWwiOiJqbWd3aXRsb3hAaG90bWFpbC5jb20ifQ.b4Gq5c-1dPRYzwKIuzrrfCEq5X0iie6NAbrZApjKWIAZ0fxt-1iJnqKc_9u94vJkN2BNojzRPvWFQnQyWx6t3a_J1LuRX2zP_P70IrHnqyM0gMc7NSpscQ6fr2iWb2UMg551OpkFaANd3DxaIeEj4QbxryloaRK2NbZSTOlxgXUOjJ_jbPJhQXXNdiIFur11D0C_hw1ABp3iCbCIz0lGwa6c6wKJRXmXKYrJ57WM9-srOYN4gArCrFkLIj_LiN6B1-hPWtgQTngXK2JPuRn75TNp0A0xHrwjsFSDxdaPw53xdLDBPkG-PenXNtW_uaoQPhu9B7l3ufXXP_Rh_quV-w',
      });
      // for (const key of req.headers.keys()) {
      //   myheaders[key] = req.headers.getAll[key];
      // }
      return next.handle(req.clone({ headers: myheaders }));
    } else {
      console.log('Er is GEEN access_token.');
      return next.handle(req.clone());
    }
  }
}
